// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AISummarize(arg1) {
  return window['go']['service']['AiService']['AISummarize'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['AiService']['Init'](arg1, arg2, arg3);
}
