// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBackupPresignedURL(arg1) {
  return window['go']['service']['BackupService']['GetBackupPresignedURL'](arg1);
}

export function Init(arg1, arg2) {
  return window['go']['service']['BackupService']['Init'](arg1, arg2);
}
