// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddGameToCategory(arg1:string,arg2:string):Promise<void>;

export function GetCategories():Promise<Array<models.Category>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;
