// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppConfig() {
  return window['go']['service']['ConfigService']['GetAppConfig']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['ConfigService']['Init'](arg1, arg2, arg3);
}

export function UpdateAppConfig(arg1) {
  return window['go']['service']['ConfigService']['UpdateAppConfig'](arg1);
}
