// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appconf} from '../models';
import {context} from '../models';
import {sql} from '../models';

export function GetAppConfig():Promise<appconf.AppConfig>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function UpdateAppConfig(arg1:appconf.AppConfig):Promise<void>;
