// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['service']['GameService']['AddCategory'](arg1);
}

export function AddGame(arg1) {
  return window['go']['service']['GameService']['AddGame'](arg1);
}

export function AddGameToCategory(arg1, arg2) {
  return window['go']['service']['GameService']['AddGameToCategory'](arg1, arg2);
}

export function DeleteGame(arg1) {
  return window['go']['service']['GameService']['DeleteGame'](arg1);
}

export function GetCategories() {
  return window['go']['service']['GameService']['GetCategories']();
}

export function GetGameByID(arg1) {
  return window['go']['service']['GameService']['GetGameByID'](arg1);
}

export function GetGames() {
  return window['go']['service']['GameService']['GetGames']();
}

export function Init(arg1, arg2) {
  return window['go']['service']['GameService']['Init'](arg1, arg2);
}

export function UpdateGame(arg1) {
  return window['go']['service']['GameService']['UpdateGame'](arg1);
}
