// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1) {
  return window['go']['service']['GameService']['AddGame'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['service']['GameService']['DeleteGame'](arg1);
}

export function FetchMetadata(arg1) {
  return window['go']['service']['GameService']['FetchMetadata'](arg1);
}

export function GetGameByID(arg1) {
  return window['go']['service']['GameService']['GetGameByID'](arg1);
}

export function GetGames() {
  return window['go']['service']['GameService']['GetGames']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['GameService']['Init'](arg1, arg2, arg3);
}

export function UpdateGame(arg1) {
  return window['go']['service']['GameService']['UpdateGame'](arg1);
}
