// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddGame(arg1:models.Game):Promise<void>;

export function AddGameToCategory(arg1:string,arg2:string):Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function GetCategories():Promise<Array<models.Category>>;

export function GetGameByID(arg1:string):Promise<models.Game>;

export function GetGames():Promise<Array<models.Game>>;

export function Init(arg1:context.Context,arg2:sql.DB):Promise<void>;

export function UpdateGame(arg1:models.Game):Promise<void>;
