// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {vo} from '../models';
import {context} from '../models';
import {sql} from '../models';
import {appconf} from '../models';

export function AddGame(arg1:models.Game):Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function FetchMetadata(arg1:vo.MetadataRequest):Promise<models.Game>;

export function GetGameByID(arg1:string):Promise<models.Game>;

export function GetGames():Promise<Array<models.Game>>;

export function Init(arg1:context.Context,arg2:sql.DB,arg3:appconf.AppConfig):Promise<void>;

export function UpdateGame(arg1:models.Game):Promise<void>;
