// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHomePageData() {
  return window['go']['service']['HomeService']['GetHomePageData']();
}

export function GetOrCreateCurrentUser() {
  return window['go']['service']['HomeService']['GetOrCreateCurrentUser']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['HomeService']['Init'](arg1, arg2, arg3);
}
