// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vo} from '../models';
import {models} from '../models';
import {context} from '../models';
import {sql} from '../models';

export function FetchMetadata(arg1:vo.MetadataRequest):Promise<models.Game>;

export function Init(arg1:context.Context,arg2:sql.DB):Promise<void>;
