// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStats() {
  return window['go']['service']['StatsService']['GetStats']();
}

export function Init(arg1, arg2) {
  return window['go']['service']['StatsService']['Init'](arg1, arg2);
}
