// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGameStats(arg1) {
  return window['go']['service']['StatsService']['GetGameStats'](arg1);
}

export function GetGlobalStats() {
  return window['go']['service']['StatsService']['GetGlobalStats']();
}

export function Init(arg1, arg2, arg3) {
  return window['go']['service']['StatsService']['Init'](arg1, arg2, arg3);
}
