// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sql} from '../models';
import {models} from '../models';

export function Init(arg1:context.Context,arg2:sql.DB):Promise<void>;

export function ReportPlaySession(arg1:models.PlaySession):Promise<void>;
